---
# DDPG good result     none:25s' priority memory:20s'
  spark_default_parallelism:
    min: 100
    max: 500
    default: 200
  spark_driver_cores:
    min: 1
    max: 6
    default: 1
  spark_driver_memory:
    min: 1024
    max: 2048
    default: 1024
  spark_reducer_maxSizeInFlight:
    min: 48
    max: 128
    default: 48
#  spark_shuffle_compress:
#    max:
#    range:
#        - "true"
#        - "false"
#    default: "true"
  spark_shuffle_file_buffer:
    min: 24
    max: 128
    default: 32
#  spark_shuffle_spill_compress:
#    max:
#    range:
#        - "false"
#        - "true"
#    default: "true"
#  spark_broadcast_compress:
#    max:
#    range:
#        - "false"
#        - "true"
#    default: "true"
#  spark_io_compression_codec:
#    max:
#    range:
#        - "lz4"
#        - "lzf"
#        - "snappy"
#    default: "lz4"
#  spark_io_compression_blockSize:
#    min: 2
#    max: 128
#    default: 32
#  spark_rdd_compress:
#    max:
#    range:
#        - "true"
#        - "false"
#    default: "false"
  spark_serializer:
    max:
    range:
        - "org.apache.spark.serializer.KryoSerializer"
        - "org.apache.spark.serializer.JavaSerializer"
    default: "org.apache.spark.serializer.JavaSerializer"
  spark_memory_fraction:
    min: 0.5
    max: 0.8
    float: yes
    default: 0.6
  spark_memory_storageFraction:
    min: 0.3
    max: 0.8
    float: yes
    default: 0.5
  spark_broadcast_blockSize:
    min: 2
    max: 128
    default: 4

#================yarn===================
  yarn_executor_num:
    min: 2
    max: 6
    default: 2
  yarn_executor_core:
    min: 2
    max: 6
    default: 2
  spark_executor_memory:
    min: 2048
    max: 4096
    default: 2048
  spark_yarn_am_memory:
    min: 512
    max: 1024
    default: 512
  spark_yarn_am_cores:
    min: 2
    max: 4
    default: 2
#    index:0-19    0-12
#    spark.conf----------------------
#  yarn_scheduler_maximum_allocation_mb:
#    min: 6000
#    max: 12288
#    default: 8192
#  yarn_scheduler_minimum_allocation_mb:
#    min: 1024
#    max: 2048
#    default: 1024
#  yarn_nodemanager_resource_memory_mb:#######################
#    min: 4096
#    max: 12288
#    default: 8192
#    设置该节点上yarn可使用的内存，默认为8G，如果节点内存不足8G，要减少这个值，
#      yarn不会智能的去检测内存资源，一般这个值式yarn的可用内存资源。
#  yarn_nodemanager_vmem_pmem_ratio:
#    min: 2.1
#    max: 5
#    float: yes
#    default: 2.1
#  yarn_nodemanager_resource_cpu_vcores:####################
#    min: 4
#    max: 12
#    default: 8
#  yarn_scheduler_minimum_allocation_vcores:
#    min: 1
#    max: 4
#    default: 1
#  yarn_scheduler_maximum_allocation_vcores:
#    min: 6
#    max: 12
#    default: 8
#    index 20-26
#    表示该节点服务器上yarn可以使用的虚拟的CPU个数，默认是8，推荐配置与核心个数相同，
#    如果节点CPU的核心个数不足8个，需要调小这个值，yarn不会智能的去检测物理核数。如果机器性能较好，可以配置为物理核数的2倍
# yarn-site.xml
#===============hdfs=========================
#  dfs_replication:
#    min: 1
#    max: 4
#    default: 1
  dfs_namenode_handler_count:
    min: 10
    max: 40
    default: 10
#  dfs_datanode_handler_count:
#    min: 10
#    max: 40
#    default: 10
#  dfs_datanode_du_reserved:
#    min: 0
#    max: 131072
#    default: 0
  dfs_datanode_max_transfer_threads:
    min: 3000
    max: 8192
    default: 4096
#  dfs_blocksize:
#    max:
#        range:
#            - 64
#            - 128
#            - 256
#        default: 128
#        m
  dfs_datanode_balance_bandwidthPerSec:
    min: 1048576
    max: 52428800
    default: 10485760
#      1m 50m 10m
  #    index 27-32
#  core.site.xml
#  io_file_buffer_size:
#    min: 4096
#    max: 131072
#    default: 4096
#    index:33
#